name: Update Google Scholar Stats

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-scholar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r google_scholar_crawler/requirements.txt
    
    - name: Run Google Scholar crawler
      run: |
        cd google_scholar_crawler
        python update_scholar.py
      continue-on-error: true  # Don't fail if Google Scholar is temporarily unavailable
    
    - name: Check if data was fetched
      id: check_data
      run: |
        if [ -f "google_scholar_crawler/google-scholar-stats/gs_data.json" ]; then
          echo "data_exists=true" >> $GITHUB_OUTPUT
        else
          echo "data_exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Configure Git
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Checkout google-scholar-stats branch
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        git checkout google-scholar-stats || git checkout -b google-scholar-stats
    
    - name: Copy updated data
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        cp google_scholar_crawler/google-scholar-stats/*.json .
    
    - name: Commit and push changes
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        git add *.json
        git diff --staged --quiet || git commit -m "Update Google Scholar stats - $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin google-scholar-stats --force
    
    - name: Summary
      run: |
        echo "## Google Scholar Update Summary" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.check_data.outputs.data_exists }}" == "true" ]; then
          echo "✅ Successfully updated Google Scholar data" >> $GITHUB_STEP_SUMMARY
          if [ -f "google_scholar_crawler/google-scholar-stats/gs_data.json" ]; then
            echo "### Statistics:" >> $GITHUB_STEP_SUMMARY
            python -c "import json; data = json.load(open('google_scholar_crawler/google-scholar-stats/gs_data.json')); print(f'- Total Citations: {data.get(\"citedby\", 0)}'); print(f'- H-index: {data.get(\"hindex\", 0)}'); print(f'- Publications: {len(data.get(\"publications\", {}))}')" >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "⚠️ Google Scholar data fetch failed or was skipped" >> $GITHUB_STEP_SUMMARY
        fi