name: Get Citation Data

on: 
 page_build: 
 workflow_dispatch:
 push:
   branches: [ main ]
 schedule:
  - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add timeout to prevent hanging
    steps:
    - uses: actions/checkout@v3  # Update to v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        cd ./google_scholar_crawler
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Google Scholar crawler
      timeout-minutes: 2  # Shorter timeout
      continue-on-error: true  # Don't fail the workflow
      run: |
        cd ./google_scholar_crawler
        echo "Attempting to fetch Google Scholar data..."
        # Create minimal data first as backup
        mkdir -p results
        cat > results/gs_data.json << 'EOF'
        {
          "name": "Shiyang Zhang",
          "affiliation": "Yale University", 
          "email": "harryzhang957@gmail.com",
          "citedby": 0,
          "citedby5y": 0,
          "hindex": 0,
          "hindex5y": 0,
          "i10index": 0,
          "i10index5y": 0,
          "updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "publications": {},
          "note": "Data will be updated when Google Scholar becomes accessible"
        }
        EOF
        echo '{"schemaVersion":1,"label":"citations","message":"0"}' > results/gs_data_shieldsio.json
        
        # Try to run the crawler with very short timeout
        timeout 30s python3 simple_crawler.py || echo "Crawler timed out - using default data"
        
        echo "Contents of gs_data.json:"
        cat results/gs_data.json | head -20
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: Push to google-scholar-stats branch
      run: |
        cd ./google_scholar_crawler/results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:google-scholar-stats --force