name: Test Secret Setup

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check if secret exists
      run: |
        if [ -z "${{ secrets.GOOGLE_SCHOLAR_ID }}" ]; then
          echo "❌ ERROR: GOOGLE_SCHOLAR_ID secret is not set!"
          echo "Please add it in Settings > Secrets > Actions"
          exit 1
        else
          echo "✅ SUCCESS: GOOGLE_SCHOLAR_ID secret is properly configured!"
          echo "Secret length: ${#GOOGLE_SCHOLAR_ID}"
        fi
      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
